/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzymulticriteriadecisionmaking;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author gonzalowtf
 */
public class addCriteria extends javax.swing.JInternalFrame {

    /**
     * Creates new form addDecisor
     */
    int idproblem =0;
    public addCriteria(String name) {
        
        initComponents();
        setTitle("Add a new Criteria to "+name.substring(1)+ " ?");
                
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
       
        //JOptionPane.showMessageDialog(null, name.substring(1));

        try{
        Conn cn = new Conn(url);
         //cn.c.setAutoCommit(false);
        cn.stmt = cn.c.createStatement();
        String sql = "Select idproblem from problems where name ='"+name.substring(1)+"'";
        ResultSet rs = cn.stmt.executeQuery(sql);
         int idp =0;
        
        while(rs.next()){
               idp= rs.getInt(1);
               idproblem = idp;
               //JOptionPane.showMessageDialog(null,idp);
            }
        
        cn.stmt.close();
        cn.c.close();
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }        
        
        
         

        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        name = new javax.swing.JTextField();

        jLabel1.setText("Enter Criteria name:");

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(add))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.hide();
    }//GEN-LAST:event_cancelActionPerformed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      if(this.name.getText()== ""){
             JOptionPane.showMessageDialog(null, "Please Enter a Criteria name  ");

        }
        else{
            
        
        try{
            
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        String name = this.name.getText();
        Conn cn = new Conn(url);
        cn.stmt = cn.c.createStatement();
        String sql = "insert into criterias values (null, '"+name.trim().toUpperCase()+"', "+idproblem+")";
        cn.stmt.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, "Criteria Added");
        this.hide();
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
        }
           
           
   }
        
        
        
    }//GEN-LAST:event_nameKeyPressed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
         if(this.name.getText()== ""){
             JOptionPane.showMessageDialog(null, "Please Enter a Criteria name  ");

        }
        else{
            
        
        try{
            
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        String name = this.name.getText();
        Conn cn = new Conn(url);
        cn.stmt = cn.c.createStatement();
        String sql = "insert into criterias values (null, '"+name+"', "+idproblem+")";
        cn.stmt.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, "Criteria Added");
        this.hide();
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
        }
    }//GEN-LAST:event_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
