/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzymulticriteriadecisionmaking;

import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author gonzalowtf
 */
public class Weights extends javax.swing.JInternalFrame {

    /**
     * Creates new form Weights
     */
    public Weights() {
        initComponents();
        setTitle("Weights");
        this.va.removeAllItems();
        this.vd.removeAllItems();
        this.vc.removeAllItems();
        this.a1.setEditable(false);
        this.a2.setEditable(false);
        this.a3.setEditable(false);
        this.c1.setEditable(false);
        this.c2.setEditable(false);
        this.c3.setEditable(false);
        this.d1.setEditable(false);
        this.d2.setEditable(false);
        this.d3.setEditable(false);
        //this.vd.addItem(" ");
        //this.vc.addItem(" ");
        //this.va.addItem(" ");
        this.savea.setEnabled(false);
        this.saved.setEnabled(false);
        this.savec.setEnabled(false);

        
        try{
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        Conn cn = new Conn(url);
                    //cn.c.setAutoCommit(false);
                    cn.stmt = cn.c.createStatement();
                    String sql = "Select name from weights where kind ='decisors'";
                    ResultSet rs = cn.stmt.executeQuery(sql);
                    
                    while(rs.next()){
                        this.vd.addItem(rs.getString(1));
                    }
                    cn.stmt.close();
                    rs.close();
                    cn.c.close();
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
        
        
         try{
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        Conn cn = new Conn(url);
                    //cn.c.setAutoCommit(false);
                    cn.stmt = cn.c.createStatement();
                    String sql = "Select name from weights where kind ='criterias'";
                    ResultSet rs = cn.stmt.executeQuery(sql);
                    
                    while(rs.next()){
                        this.vc.addItem(rs.getString(1));
                    }
                    cn.stmt.close();
                    rs.close();
                    cn.c.close();
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
        
         
          try{
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        Conn cn = new Conn(url);
                    //cn.c.setAutoCommit(false);
                    cn.stmt = cn.c.createStatement();
                    String sql = "Select name from weights where kind ='alternatives'";
                    ResultSet rs = cn.stmt.executeQuery(sql);
                    
                    while(rs.next()){
                        this.va.addItem(rs.getString(1));
                    }
                    cn.stmt.close();
                    rs.close();
                    cn.c.close();
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        vc = new javax.swing.JComboBox<>();
        vd = new javax.swing.JComboBox<>();
        va = new javax.swing.JComboBox<>();
        savea = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        d3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        c2 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        a3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ea = new javax.swing.JButton();
        ec = new javax.swing.JButton();
        ed = new javax.swing.JButton();
        savec = new javax.swing.JButton();
        saved = new javax.swing.JButton();

        jLabel4.setText("Decisors");

        jLabel5.setText("Criterias");

        jLabel6.setText("Alternatives");

        vc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vcItemStateChanged(evt);
            }
        });

        vd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vdItemStateChanged(evt);
            }
        });
        vd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vdMouseClicked(evt);
            }
        });

        va.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        va.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vaItemStateChanged(evt);
            }
        });

        savea.setText("Save");
        savea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveaActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("(");

        jLabel2.setText("-");

        jLabel3.setText("-");

        jLabel8.setText("(");

        jLabel9.setText("-");

        jLabel10.setText("-");

        jLabel12.setText("-");

        jLabel13.setText("(");

        jLabel14.setText("-");

        jLabel15.setText("  )");

        jLabel16.setText("  )");

        jLabel17.setText("  )");

        ea.setText("Edit");
        ea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaActionPerformed(evt);
            }
        });

        ec.setText("Edit");
        ec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecActionPerformed(evt);
            }
        });

        ed.setText("Edit");
        ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edActionPerformed(evt);
            }
        });

        savec.setText("Save");
        savec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savecActionPerformed(evt);
            }
        });

        saved.setText("Save");
        saved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(va, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(ea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savea)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jSeparator1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ed)
                .addGap(18, 18, 18)
                .addComponent(saved)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(vc, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(ec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savec)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(vd, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(638, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel17)
                    .addComponent(ed)
                    .addComponent(saved))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16)
                    .addComponent(ec)
                    .addComponent(savec))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(va, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(ea)
                    .addComponent(savea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(vd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(439, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.hide();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaActionPerformed
        this.a1.setEditable(true);
        this.a2.setEditable(true);
        this.a3.setEditable(true);
        this.savea.setEnabled(true);
    }//GEN-LAST:event_eaActionPerformed

    private void ecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecActionPerformed
        this.c1.setEditable(true);
        this.c2.setEditable(true);
        this.c3.setEditable(true);
        this.savec.setEnabled(true);
    }//GEN-LAST:event_ecActionPerformed

    private void edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edActionPerformed
        this.d1.setEditable(true);
        this.d2.setEditable(true);
        this.d3.setEditable(true);
        this.saved.setEnabled(true);
    }//GEN-LAST:event_edActionPerformed

    private void vdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vdItemStateChanged
        
        //JOptionPane.showMessageDialog(null, this.vd.getSelectedItem().toString());
        if ( evt.getStateChange() == ItemEvent.SELECTED){
        try{
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        Conn cn = new Conn(url);
                    //cn.c.setAutoCommit(false);
                    cn.stmt = cn.c.createStatement();
                    String sql = "Select w1,w2,w3 from weights where kind ='decisors' and name = '"+this.vd.getSelectedItem().toString()+"'";
                    ResultSet rs = cn.stmt.executeQuery(sql);
                    double w1 =0;
                    double w2 =0;
                    double w3 =0;
                    while(rs.next()){
                       w1 = rs.getDouble(1);
                       w2 = rs.getDouble(2);
                       w3 = rs.getDouble(3);
                    }
                    this.d1.setText(String.valueOf(w1));
                    this.d2.setText(String.valueOf(w2));
                    this.d3.setText(String.valueOf(w3));
                    cn.stmt.close();
                    rs.close();
                    cn.c.close();
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
        }
        
    }//GEN-LAST:event_vdItemStateChanged

    private void vdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vdMouseClicked
        
        
    }//GEN-LAST:event_vdMouseClicked

    private void vcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vcItemStateChanged
        //JOptionPane.showMessageDialog(null, this.vd.getSelectedItem().toString());
        if ( evt.getStateChange() == ItemEvent.SELECTED){
        try{
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        Conn cn = new Conn(url);
                    //cn.c.setAutoCommit(false);
                    cn.stmt = cn.c.createStatement();
                    String sql = "Select w1,w2,w3 from weights where kind ='criterias' and name = '"+this.vc.getSelectedItem().toString()+"'";
                    ResultSet rs = cn.stmt.executeQuery(sql);
                    double w1 =0;
                    double w2 =0;
                    double w3 =0;
                    while(rs.next()){
                       w1 = rs.getDouble(1);
                       w2 = rs.getDouble(2);
                       w3 = rs.getDouble(3);
                    }
                    this.c1.setText(String.valueOf(w1));
                    this.c2.setText(String.valueOf(w2));
                    this.c3.setText(String.valueOf(w3));
                    cn.stmt.close();
                    rs.close();
                    cn.c.close();
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
        }
    }//GEN-LAST:event_vcItemStateChanged

    private void vaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vaItemStateChanged
        //JOptionPane.showMessageDialog(null, this.vd.getSelectedItem().toString());
        if ( evt.getStateChange() == ItemEvent.SELECTED){
        try{
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        Conn cn = new Conn(url);
                    //cn.c.setAutoCommit(false);
                    cn.stmt = cn.c.createStatement();
                    String sql = "Select w1,w2,w3 from weights where kind ='alternatives' and name = '"+this.va.getSelectedItem().toString()+"'";
                    ResultSet rs = cn.stmt.executeQuery(sql);
                    double w1 =0;
                    double w2 =0;
                    double w3 =0;
                    while(rs.next()){
                       w1 = rs.getDouble(1);
                       w2 = rs.getDouble(2);
                       w3 = rs.getDouble(3);
                    }
                    this.a1.setText(String.valueOf(w1));
                    this.a2.setText(String.valueOf(w2));
                    this.a3.setText(String.valueOf(w3));
                    cn.stmt.close();
                    rs.close();
                    cn.c.close();
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
        }
    }//GEN-LAST:event_vaItemStateChanged

    private void savedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedActionPerformed
       
        
        double w1 = Double.parseDouble(this.d1.getText());
        double w2 = Double.parseDouble(this.d2.getText());
        double w3 = Double.parseDouble(this.d3.getText());
        try{
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        Conn cn = new Conn(url);
                    //cn.c.setAutoCommit(false);
                    cn.stmt = cn.c.createStatement();
                    String sql = "update weights set w1 = "+w1+" ,w2 ="+w2+" ,w3 = "+w3+" where kind = 'decisors' and name ='"+this.vd.getSelectedItem().toString()+"'";
                    
                    cn.stmt.executeUpdate(sql);
                    cn.stmt.close();
                    cn.c.close();
                    JOptionPane.showMessageDialog(null, "Triangle Changed !");
                    this.d1.setEditable(false);
                    this.d2.setEditable(false);
                    this.d3.setEditable(false);
                    this.saved.setEnabled(false);
                    
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
                
        
    }//GEN-LAST:event_savedActionPerformed

    private void savecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savecActionPerformed
         double w1 = Double.parseDouble(this.d1.getText());
        double w2 = Double.parseDouble(this.d2.getText());
        double w3 = Double.parseDouble(this.d3.getText());
        try{
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        Conn cn = new Conn(url);
                    //cn.c.setAutoCommit(false);
                    cn.stmt = cn.c.createStatement();
                    String sql = "update weights set w1 = "+w1+" ,w2 ="+w2+" ,w3 = "+w3+" where kind = 'criterias' and name ='"+this.vc.getSelectedItem().toString()+"'";
                    
                    cn.stmt.executeUpdate(sql);
                    cn.stmt.close();
                    cn.c.close();
                    JOptionPane.showMessageDialog(null, "Triangle Changed !");
                    this.c1.setEditable(false);
                    this.c2.setEditable(false);
                    this.c3.setEditable(false);
                    this.savec.setEnabled(false);
                    
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
    }//GEN-LAST:event_savecActionPerformed

    private void saveaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveaActionPerformed
         double w1 = Double.parseDouble(this.d1.getText());
        double w2 = Double.parseDouble(this.d2.getText());
        double w3 = Double.parseDouble(this.d3.getText());
        try{
        String url = System.getProperty("user.dir") + "\\datafuzzy.db";
        Conn cn = new Conn(url);
                    //cn.c.setAutoCommit(false);
                    cn.stmt = cn.c.createStatement();
                    String sql = "update weights set w1 = "+w1+" ,w2 ="+w2+" ,w3 = "+w3+" where kind = 'alternatives' and name ='"+this.va.getSelectedItem().toString()+"'";
                    
                    cn.stmt.executeUpdate(sql);
                    cn.stmt.close();
                    cn.c.close();
                    JOptionPane.showMessageDialog(null, "Triangle Changed !");
                    this.a1.setEditable(false);
                    this.a2.setEditable(false);
                    this.a3.setEditable(false);
                    this.savea.setEnabled(false);
                    
        }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, "Data Base Connection Problem (new p 208) "+ err.toString());
                }
    }//GEN-LAST:event_saveaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField d3;
    private javax.swing.JButton ea;
    private javax.swing.JButton ec;
    private javax.swing.JButton ed;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton savea;
    private javax.swing.JButton savec;
    private javax.swing.JButton saved;
    private javax.swing.JComboBox<String> va;
    private javax.swing.JComboBox<String> vc;
    private javax.swing.JComboBox<String> vd;
    // End of variables declaration//GEN-END:variables
}
